### ISSUE TITLE
課題の登録時の「詳細」が長すぎるとエラーを起こします。

### ISSUE THREAD

**Issue by ibexorg** [codeforkanazawa-org/ha4go#100]
長過ぎるとエラーを起こします。現状の文字数は不明（多分250文字程度）でエラーになりますが、400文字程度は入力したいです。
また、長すぎる場合はエラーチェックを入れて、入力欄下あたりに「400文字以内でお書きください」的なガイダンス文があると良いかも。

**Comment by ibexorg** [comment]
あ、私じゃマイルストーン変えれない...Release-201607に対応できないと困るかもです。

**Comment by PharaohKJ** [comment]
65,535文字まで対応。

**Comment by ibexorg** [comment]
※今週末確認

**Comment by ibexorg** [comment]
大丈夫そうなのでクローズします。
