### ISSUE TITLE
シェアボタンでFbに書き込まれた場合、Fbのプレビュー表示は課題のタイトルの方が良い

### ISSUE THREAD

**Issue by ibexorg** [codeforkanazawa-org/ha4go#101]
シェアした場合、件名はシェアされた課題の件名の方がわかりやすいと思います。
現状は

ha4go
課題を深く知る市民とシビックテックとの情報交換サイト、はじめました。

となっています。

**Comment by PharaohKJ** [comment]
72bfb9e3e5d7289919d68c456ba7df16b67f2c60
あたりですでに対応済み。
