### ISSUE TITLE
Fbシェアのカウント表示が正しくない

### ISSUE THREAD

**Issue by ibexorg** [codeforkanazawa-org/ha4go#102]
１回しかシェアしていないのに、２とか３とかになっています。
それほど優先順位は高くないです。
![test](https://cloud.githubusercontent.com/assets/7151911/15234635/b8740264-18ee-11e6-817f-ce9535d7d919.png)

**Comment by PharaohKJ** [comment]
https://kanazawa.ha4go.net/projects/2

で試しましたが、大丈夫そうです。どうでしょう？ただ、シェアしてもFB上で表示されるのがトップページに関する情報になってしまってるバグはありますね。

**Comment by ibexorg** [comment]
大丈夫そうですね。
#101 にトップページの件ありますので、これはクローズします。
