### ISSUE TITLE
CfA向けRSS作成機能

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#11]

**Comment by PharaohKJ** [comment]
とりあえず

http://<address>/feed

でrssを取得できるようになったけれど、フォーマット、内容については要調査。

fb上で sample をきく。

**Comment by kiyohara** [comment]
https://github.com/codeforamerica/cfapi

この辺を参考にすると良いらしい。

**Comment by PharaohKJ** [comment]
https://github.com/codeforamerica/brigade-information

こっちのがやりたいことなのかな？なんか json or csv 作っておいてくれと書いてあるように読めます。

@ibexorg さん、どこをどう参考にしてこれ実装すればいいか教えて下さい。

いったん RSS は RSS で別に実装しておきます。私が欲しいので。

**Comment by kenchif** [comment]
福島の方からコメントします。

https://github.com/codeforamerica/brigade-information/blob/master/organizations.json
上記の中にCode for Kanazawaは登録されています。574行〜584行目までです。
rss欄は空欄になっているので、プルリクをしてここにRSSのフィードを登録する形になります。
以上で完了です。

ただ、今あらためてこのあたりをチェックして気づいたのですが、Code for AmericaとBrigade（いわゆる地域団体）との関係がうまくいかなくなったこともあってか、現在のCode for AmericaのWebページから下記のBrigadeページが見つけられませんでした（どこかにあるのかもしれませんが）。
https://www.codeforamerica.org/brigade/

現在のCode for Americaのページは以下で、構成が昔と変わってきています。
https://www.codeforamerica.org/

で、何が言いたいかというと、RSSの情報がしっかり掲載されるページができるのか分からない感じです。
なお、昔はこんな感じで出てました。Current Storiesのところがそうです。
https://www.codeforamerica.org/brigade/Beta-NYC/

ちなみに、Code for Kanazawaはこういうページになっています。GitHubの情報は登録してあるので自動的に吸い取られています。
https://www.codeforamerica.org/brigade/Code-for-Kanazawa/

@ibexorg さん、このあたりどう考えます？どう動くか判断が必要かと。

**Comment by PharaohKJ** [comment]
ちょっと別。以下のチェッカーでちゃんとチェックすること

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fkanazawa.ha4go.net%2Fprojects%2F11

**Comment by ibexorg** [comment]
@PharaohKJ さん
サンプルを見つけましたが、CfAで利用しているように見えないので、我々で使わないのであれば優先度をかなり下げるor開発中止するでもよいのかなと思います。
https://groups.google.com/forum/feed/code-for-san-francisco/msgs/rss.xml

**Comment by PharaohKJ** [comment]
@ibexorg 
もう RSS は出力してます。

`<ha4goのurl>/feed.rss`
`<ha4goのurl>//projects/<project番号>.rss`

で読めます。

CfA に出展したい？など @ibexorg さんの要望があってその形式にしようとこの issue がたちましたが、
もう使わない確定、もしくは、他の方法にするべきならば、ここでクローズしてしまいましょう。

**Comment by ibexorg** [comment]
いったん現状のままでクローズしましょう。
