### ISSUE TITLE
未ログイン状態で課題詳細でログインすると、トップページにもどる

### ISSUE THREAD

**Issue by ibexorg** [codeforkanazawa-org/ha4go#119]
ログインしていない状態で、課題詳細画面を表示するとログインボタンがあるのですが、そのボタンでログインするとトップページにもどってしまいます。
多分ユーザーはそのページにとどまり続けたいと思います。

**Comment by PharaohKJ** [comment]
対応したので確認お願いします。

**Comment by ibexorg** [comment]
修正を確認しました。ありがとうございます。
