### ISSUE TITLE
モバイルでプルダウン（ログインボタンとか周り）がずれてる

### ISSUE THREAD

**Issue by ibexorg** [codeforkanazawa-org/ha4go#121]
by @masayoshimatsuo 
モバイルでログイン前はOKで、ログイン後にずれるそうです。
![13735402_1123370511034437_2001204827_n](https://cloud.githubusercontent.com/assets/7151911/16895646/99df36a0-4bb8-11e6-8a4d-a15a418c386d.png)

**Comment by PharaohKJ** [comment]
@masayoshimatsuo @ibexorg  ごめんなさい、何がずれてるのかイマイチよくわかりません。
私の iPhone6 plus だとモバイルメニューになって再現できませんでした。

具体的に使ってる端末とブラウザを教えてほしいです。

とりあえず、メディアクエリの横幅がおそらく数字間違えてしまっていたので 780 → 960pxにしたので
あとで確認してみてほしいです。

**Comment by PharaohKJ** [comment]
@ibexorg 催促。

**Comment by PharaohKJ** [comment]
@ibexorg 催促 2nd impact.

**Comment by ibexorg** [comment]
![screenshot_20160922-084938](https://cloud.githubusercontent.com/assets/7151911/18733241/1d00e4fa-80a4-11e6-8cc2-776bf82f07f5.png)

**Comment by ibexorg** [comment]
メニューと点線円をつなぐ上向き三角が真ん中に来てない、ということだそうです。
遅くなりました。

**Comment by PharaohKJ** [comment]
うーん @masayoshimatsuo さんからいただいたものからこのように表示されているので、理想形がわからないのですが、たぶんここが間違いだろうというのを修正しました。

具体的には△が、プルダウンメニューの縦サイズに比例して場所を変えてしまう(パーセント指定だった)のを絶対値(ピクセル指定)に変更しました。とりあえずログイン前とログイン後と動作は同じにできました。

**Comment by ibexorg** [comment]
確認しました。
ありがとうございます。クローズします。
