### ISSUE TITLE
英数字やURLなどが改行されない。

### ISSUE THREAD

**Issue by ibexorg** [codeforkanazawa-org/ha4go#122]
既知ですが、Issueにします。
@masayoshimatsuo さんによると、
overflow-wrap
でとのこと
body{
　　overflow-wrap: break-word;
}
で試してみて、とのことでした。
[参考](http://boxlife.net/hamidasu_css/)

**Comment by PharaohKJ** [comment]
対応しました。が、1行css追加するだけならぜひプルリクにチャレンジしてみてください。

https://github.com/codeforkanazawa-org/ha4go/blob/master/app/assets/stylesheets/matsu/style.scss

あたりです。
