### ISSUE TITLE
「直近」のしきい値を変更するのは誰か

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#125]
> 最近の課題 直近30日以内(閾値・変更可）にコメントがあった課題

しきい値を変更するのは誰ですか。

- ユーザー？
- サイト管理者？
- サイト管理者が標準値を設定し、ユーザーがそれぞれ設定？

**Comment by ibexorg** [comment]
#126 重複ですかね？

**Comment by PharaohKJ** [comment]
プロダクトバックログの内容をもっとより具体的にしていただければOKでっす。
この機能の「直近」と、#126 の「直近」と意味・機能が同じかハッキリしてない感じであって、重複ではないです。

2016年8月11日(木) 19:06 takashi torige <notifications@github.com>:

**Comment by PharaohKJ** [comment]
とりま現在はコード埋め込みで完了。 `ApplicationController`.`default_duration` 参照。
