### ISSUE TITLE
「話題になっている課題」しきい値を変更するのは誰か

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#126]
> 話題になっている課題 課題別に直近のコメントが100件(閾値・変更可）のうち、上位ランクをつけ3位以内(閾値・変更可）。

しきい値・直近の範囲・ｎ位内をしきい値を変更・設定するのはそれぞれ誰ですか？

- ユーザー？
- サイト管理者？
- サイト管理者が標準値を設定し、ユーザーがそれぞれ設定？

**Comment by ibexorg** [comment]
サイト管理者でOKです。

**Comment by PharaohKJ** [comment]
とりま現在はコード埋め込みで完了。 `ApplicationController`.`default_duration` 参照。
