### ISSUE TITLE
課題の新規登録、課題のスキル編集時にスキルマッチングをして招待する。

### ISSUE THREAD

**Issue by ibexorg** [codeforkanazawa-org/ha4go#132]
ProductBackLog 2016.10版　1.課題への招待機能を加える
・課題を新しく登録するときに全てのスキル
・課題のスキルを変更したとき（前回比較し、追加されたとき）の追加分のスキル
にプロフィールのスキルにマッチした相手にメールを送る
※ただし１人にメールが重複しないように..

メール本文には
・課題を新しく登録するときに全てのスキル
→あなたのスキルにマッチした課題が登録されました。

・課題のスキルを変更したとき（前回比較し、追加されたとき）の追加分のスキル
→あなたのスキルを求めている課題があります。

**Comment by ibexorg** [comment]
申し訳ない。独りでテストできない（本人にはメールが飛ばない）ので、@PharaohKJ さんのスキルの”デザイン”で課題を更新したのでメールが飛んでいるか、飛んでいたら本文を貼り付けてもらえますか？

**Comment by PharaohKJ** [comment]
![2016-11-05 22 19 23](https://cloud.githubusercontent.com/assets/1581985/20030323/02cd18c2-a3a6-11e6-86a9-d4bdf3b80d2f.png)

**Comment by PharaohKJ** [comment]
@ibexorg メールきましたよ。スクショはっておきました。 inbox + chrome です。

**Comment by PharaohKJ** [comment]
https://kanazawa.ha4go.net/projects/2

で デリバリーリードを on/off してメール飛ばしてみました。どうでしょ。

**Comment by ibexorg** [comment]
OK！
ありがとうございました。クローズしますね。
