### ISSUE TITLE
課題のステータスについてガイドラインを書く

### ISSUE THREAD

**Issue by ibexorg** [codeforkanazawa-org/ha4go#135]

**Comment by ibexorg** [comment]
メモ：ロールについても#103がリリースされるならば、合わせて書く。

**Comment by ibexorg** [comment]
【初版】
議論と調査
課題の根本原因を探っている場合はこのステータスにしましょう。
最初は課題を大きく掴み、情報を集めましょう。そしてできれば現場の見て当事者の声を聞き、課題で困っている人たちを具体的にしましょう。
そして課題を上位３つまで書き出してみましょう。
最後にプロジェクト化する為に、このプロジェクトの独自の価値を書き出してみましょう。

企画と試作中
解決する方法を検討し始めることができたらこのステータスにしましょう。
複数の解決方法がある場合は上位３つまでに絞りましょう。
そして課題で困っている人たちにどうやって知ってもらい、届けるのかも考えましょう。
最小限の試作を作り実際に見てもらうとより良くなります。

運用中
リリースしたらこのステータスにしましょう。
使っている人たちの声を聞き、細かく改善していくとより良いものになっていくでしょう。

　
休止・終了
課題が解決した場合、活動を休止する場合はこのステータスにしましょう。休止・終了にすると新規の参加者を受け付けません。
休止にしても課題投稿者はいつでも他のステータスにして再開することができます。

**Comment by ibexorg** [comment]
マニュアルに含める（のがいいのか？）

**Comment by PharaohKJ** [comment]
ステータスの意味をどこに置きたいのですか。

ドキュメントをどこに置くかのガイドラインを決めないといけない?

- gh-pages に置く
- wiki に置く
- アプリ中にいれる
  - アプリのバージョンと整合性がとれて一番いいかもだけど、アプリ作れる人しか更新できない

のどれかだと思いますが、どれがいいですか? どういった文章をどこに置くべきか決めましょう。

**Comment by ibexorg** [comment]
使い分け
* gh-pages=プロダクトとしてのha4go共通のもの
* wiki=開発用のドキュメント、新しい文章はここで書いて各所に転記する（gh-pages or アプリ or wikiにそのまま)
* アプリの中に入れる=ローカライズ後に使うときに変わるもの

ステータスはローカライズしたくなる可能性がありますが、ha4go共通でgh-pagesでいいような気がします。
