### ISSUE TITLE
課題作成時の画面でポリシー同意のチェックを入れる

### ISSUE THREAD

**Issue by ibexorg** [codeforkanazawa-org/ha4go#136]
課題作成の画面において、作成ボタンの上部にチェックボックスを設け
「当課題の成果物はコードフォーカナザワに帰属いたします。」
という文面をつける。（つけたものは課題の属性として保存しておく）
当面、チェックを入れなければ作成できないようにする。（後で仕様が変わる可能性がある）

本Issueの目的は
成果物の帰属が曖昧なため、CfKへの成果物帰属が明確になっていないため、ポリシーから逸脱する可能性を排除したいため。

**Comment by PharaohKJ** [comment]
本番で確認。OK。

**Comment by PharaohKJ** [comment]
あ、でも、この文面でどう？ポリシー自体をどうする？ってのは別議論。
