### ISSUE TITLE
コメントを削除できるようにする

### ISSUE THREAD

**Issue by ibexorg** [codeforkanazawa-org/ha4go#138]
現状訂正ができないため、コメントを削除できるようにする。
1.自分が書いたコメントにアイコン（ゴミ箱のようなものをイメージ）を配置する。
2.押下した場合、以下のコメントと入れ替える
「※フォローが削除されました」
とする。

**Comment by PharaohKJ** [comment]
訂正ができないのであれこれ、というのは、回り道をしてるだけなので、修正できるようにするほうで対応します。

いったんこれクローズしてしまいます。
