### ISSUE TITLE
フォロー(コメント)を修正できるようにする

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#139]
#138 より、フォロー(コメント)を修正できるようにする。

修正した場合には

- 修正日時
- 修正したことがわかるようにする(内容の履歴はとらなくていいかな)
- 修正権限は書いた人 もしくは プロジェクトオーナー とする

**Comment by ibexorg** [comment]
ありがとうございます。
プロジェクトオーナーも修正できるならば(複数ならば)修正した人の名前も記録つけたいです。

**Comment by PharaohKJ** [comment]
フォローの編集と削除に対応(権限は、書いた本人と課題を作った人にあります)
これらを行うと、書いた人、日付がフォローのしたに表示されます。
