### ISSUE TITLE
Facebook API を CfK でたたけるように鍵などの発行を行う

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#14]
CfK 福島さんにお願いする。

**Comment by PharaohKJ** [comment]
@jshimazu さん、取得するパーミッションを @kenchif さんに教えて、取得してもらってください。

取得でき次第closeで。

**Comment by jshimazu** [comment]
@kenchif さん
Cfkのアカウントに"ha4go" Facebookアプリを作成、
@PharaohKJ さんと自分のアカウントのRoleをAdministraterに設定お願いします！

**Comment by kenchif** [comment]
@jshimazu さん
CfKは組織(ページアカウントのみ)なんですが、個人アカウントしか開発者登録できないんじゃありませんでしたっけ。個人アカウントのみだったら、お二人のどちらかで作成されるのが良いと思います。

**Comment by jshimazu** [comment]
なるほど。ということは、Cfkアカウントでアプリを作成ということはできないんですね。（ビジネスアカウントにも個人アカウントと同等の機能があると勘違いしていました・・）

では本番用アプリの登録は僕の個人アカウントで作成し、開発者のみなさん全員をAdmin権限にする形にします！

**Comment by jshimazu** [comment]
本番用のAppを作成しました。プロジェクトのメンバーは全員Adminにしています。
https://developers.facebook.com/apps/1457374534575451

**Comment by kiyohara** [comment]
ドメインに紐づくものなので、ドメイン決定待ちの状態。
milestone beta1 を割り当てておく。

**Comment by PharaohKJ** [comment]
これもうできてるというか、 @jshimazu さんのそのまま譲渡いただき、使ってるからOKね。close。
