### ISSUE TITLE
ha4go ディベロッパ向けドキュメントを作る

### ISSUE THREAD

**Issue by kiyohara** [codeforkanazawa-org/ha4go#147]
- [x] 開発環境のつくりかた
- [x] 開発を進めるときのルール（Github の PR の出し方など）

**Comment by PharaohKJ** [comment]
https://github.com/codeforkanazawa-org/ha4go/pull/162

まとめたのでレビューお願いします。

**Comment by PharaohKJ** [comment]
MPL ライセンスファイル追加しておきました。なんかこれで GitHub 上でも明記されるらしい。ファイルの元データは GitHub による自動生成です。

**Comment by kiyohara** [comment]
👍 

PR 今からチェックします。
これ、マージ自体は誰がどのタイミングでやるのがいいのかしら。

※僕がマージしてしまって、さらに物言いがつくなら別 PR にするとかでいい気がしているが… いいかな？

**Comment by PharaohKJ** [comment]
やっちゃいました。てへぺろ〜。

まぁ問題あったら再度オープンでいきましょう。
