### ISSUE TITLE
開発環境に初期データを用意したい

### ISSUE THREAD

**Issue by kimihito** [codeforkanazawa-org/ha4go#168]
このプロジェクトを興味深く拝見しています。

よりこのプロジェクトに貢献しやすいように、開発環境の場面では初期データが用意されていると便利かなと感じました。

WIPですが、[作業ブランチも用意している](https://github.com/CodeforOkinawa/ha4go/pull/1)状態です。もし問題ないようでしたら、直接このリポジトリに対してプルリクエストを作成したいんですが問題ないでしょうか？

**Comment by PharaohKJ** [comment]
おお、ありがとうございます。プルリクについては問題ありません。
動作が確認できればこちらでもマージいたします。
(ただ、ちょっと合議制で機能の要・不要などについては議論させてからになるかもしれません。
現在 WIP な @kimihito さんのそのブランチの機能については要で間違いありません。)

ブランチのコード読ませていただきました。実は facebook の uid って appid ごとに違うらしく、
@kimihito さんの gen していただいた uid とかは使えないかもしれないなと考えています。

(http://qiita.com/takaaki-mizuno/items/0eec10478188ff365297 あたりをご参照ください。)

ですが、この機能はとても助かりますので、 YAML の load を 
` if File.exist?(environment. yaml) ` としておいて、 `<environment>.yaml ` は `.gitignore` にいれて
しまい、ドキュメントを用意して各位に用意してもらう、としてはどうでしょうか。 

つまりタスクとしては

1. 各 `environment.rb` を db:seed 時に読み込んで実行されるように `db/seeds.rb` を拡張していただく
2. 各 `environment.rb` から読み込まれる 各 `<environment>.yaml` (例: development なら `development.yaml` ) は存在しなくてもエラーにしないようにする
3. `db/*.yaml` は `.gitignore` にいれておく
4. `<environment>.yaml.sample` を用意し、サンプルデータはそこにかいおく。
5.  App-Scoped-UID についての注意書きもその文中にかき、`README.md`の開発環境の作成にそれを明記する

で、どうでしょうか？とりあえず 1. と 2. だけでもご対応いただければ、そちらのブランチに 3. 〜 5. を
私がプルリクして対応、その後、本 master にマージしたいと思います。

**Comment by kimihito** [comment]
回答ありがとうございます。（そして返信遅れてすいません 🙇 ）

上記のタスク1, 2の対応したものを後ほどプルリクエスト作成します 💪 

ただ気になった点が一つあったので質問させてください 🙏 

初期データのyamlを Gitの管理下から外すのは、

> 実は facebook の uid って appid ごとに違うらしく、
@kimihito さんの gen していただいた uid とかは使えないかもしれないなと考えています。

ということが理由でしょうか？

個人的に初期データは開発でしか利用しないことを想定していたので、モデルのバリデーションをクリアすれば良いかなぐらいに考えていました。

ただ、あまりに雑な初期データでは開発環境と本番環境の実データでの見え方が違うのかなと感じたので、Omniauthで取得するであろうデータ（ ≒ Facebookログイン時に返ってくるキー）をyamlファイルにした次第でした。

@PharaohKJ さんから指示いただいたとおりのタスクをこなす予定ですので、おてすきの際に上記の質問に回答いただければと思います 🙇

**Comment by PharaohKJ** [comment]
いえいえ、お返事ありがとうございます。

初期データの yaml を git 管理から外すのは、おっしゃる通りの理由です。

実は今のところ App-Scoped-UID は一箇所だけ使ってます。

https://github.com/codeforkanazawa-org/ha4go/blob/master/app/views/users/show.html.erb#L10

ここです。個人のプロフィールページから、その人の facebook に飛べるようになってます。
将来的に他にも使うかもしれないので、いったんそこは手間かけていただこうかな。と考えました。

お手数をおかけしますがよろしくお願いします。

**Comment by kimihito** [comment]
@PharaohKJ #175 がマージされたのでこのIssueはクローズしてもいいかなーと思ったんですがどうでしょう？

**Comment by PharaohKJ** [comment]
OKです。クローズしちゃいますね。
