### ISSUE TITLE
メールサーバいらないモード

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#170]
開発のハードルを下げるため、メールサーバなくても動くようにする。
環境変数あたりで切り替える。

**Comment by kimihito** [comment]
https://github.com/ryanb/letter_opener と https://github.com/fgrehm/letter_opener_web を使うと環境変数も不要かもしれません。開発環境時であればメールを送信したことになります（かつブラウザから送信されるメールのレイアウトを確認することが可能）。
