### ISSUE TITLE
「最新の課題」に最新の課題が表示されないことがある

### ISSUE THREAD

**Issue by izawa** [codeforkanazawa-org/ha4go#174]
課題登録だけされていて、コメントが一切付いていない課題が「最新の課題」に出てこない。

**Comment by PharaohKJ** [comment]
確認したのですが、どうやらソートオーダーがめちゃくちゃで、コメントが一切ついてない課題がどこにあるか一見わからない、というバグのようです。

クエリがどんどん複雑になっちゃうので、`Project` テーブルに `last_comment_at` カラムを増やして、コメントがあるとそれを更新するようにし、それをソートして出すようにします。
