### ISSUE TITLE
ha4go.net が https 接続できない

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#177]
証明書の問題。どうしましょう。

- 案1 いまのkanazawa.ha4go.net で使ってる nginx で https://codeforkanazawa-org.github.io/ha4go/ をプロキシする
  - ha4go.net の IP は kanazawa.ha4go.net に向けて名前で切り分ける予定
- 案2 世間のみんなは気にしない。 http接続でハッピーハッピー。

他に案あれば。

**Comment by ibexorg** [comment]
静的ページだから私は気にしませんが、ダメ？

**Comment by izawa** [comment]
証明書自体は、*.ha4go.net と ha4go.net の両方に対応しているんですよね？
証明書を置く場所が github pagesだから無いというはなしですか？

**Comment by PharaohKJ** [comment]
はい。証明書はワイルドカードとったのでもったいないなーって。

そして、証明書を置く場所が github pages だからおけないようです。

**Comment by izawa** [comment]
なるほど。じゃ案1ですかねー。
(モチロンibexorgさんのスタンスでもいいですが)

**Comment by PharaohKJ** [comment]
私も気にしないOKですが、やっぱり ssl 接続だと検索エンジンが上位表示してくれるという話。
まぁ今度 @kiyohara 氏とタイミングあってもくもくできたらやっておきます。

**Comment by PharaohKJ** [comment]
ha4go のDNSのAレコードを修正してください。それであとは settings から設定できる模様。

 >  The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/.

**Comment by kiyohara** [comment]
@PharaohKJ 以下、対応した

https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider

手元で `dig +noall +answer ha4go.net` やるとまだ 192.30.252.153 と 192.30.252.154 の A が返ってくるが、まあそのうち反映されると思う。

**Comment by PharaohKJ** [comment]
https://ha4go.net

できてるぞ！ありがとう。
