### ISSUE TITLE
ダッシュボードに自分の作成していない「あなたの作成した課題の更新状況」が出て来る

### ISSUE THREAD

**Issue by izawa** [codeforkanazawa-org/ha4go#185]
ダッシュボード中「あなたの作成した課題の更新状況」に、
自分が作成していない課題の状況も出てきてしまう。

下記スクリーンショットでは、
加藤さんの作成した「課題と対応する解決案、プロジェクト進捗の見える化 」と
鳥毛さんの作成した「能登地域の獣害(イノシシ）対策 (最新10件)」が見えている。

<img width="634" alt="2016-12-05 09 51 35" src="https://cloud.githubusercontent.com/assets/340622/20870736/7ac0ed86-bad0-11e6-8444-366d4d1d12f8.png">

**Comment by PharaohKJ** [comment]
私の手元で動作確認したのですが、普通に動いちゃってますね・・・。ソースコードを読んでも問題なさそう。

と思ったらウソでした。これ「自分の参加している課題の更新状況」になっていますね。

すぐになおします。

**Comment by PharaohKJ** [comment]
デプロイまでしました。すみませんが @izawa さん、確認して問題なさそうなら close してください。

**Comment by izawa** [comment]
ありがとうございます！バッチシです！
クローズしますね。
