### ISSUE TITLE
facebook連携で、課題投稿者と一般フォローで投稿される内容がちがう

### ISSUE THREAD

**Issue by ibexorg** [codeforkanazawa-org/ha4go#193]
触ってて気づきましたが、
課題を投稿した本人がフォローを書くとFbページにはkanazawa.ha4go.netと表示され
本人以外がフォローを書くと、課題のタイトルも表示されます。

課題のタイトルまで表示されるように統一したほうがgood。
![issue1](https://cloud.githubusercontent.com/assets/7151911/22179497/0ebf26ae-e099-11e6-8a01-fbf93700fe75.png)
![issue2](https://cloud.githubusercontent.com/assets/7151911/22179498/10a729a8-e099-11e6-8844-3ceacefcbb59.png)

**Comment by PharaohKJ** [comment]
あざっす。なんでだろ。2月になおしちゃいますね。

**Comment by PharaohKJ** [comment]
コード読んだらたぶん課題のタイトルがでているのはたまたまで、いろいろとポストする内容を省略しちゃってるのをちゃんと指定すればコントロールできそう。

**Comment by PharaohKJ** [comment]
![2017-02-05 09 02 00](https://cloud.githubusercontent.com/assets/1581985/22622593/de4b2510-eb81-11e6-9b22-a5a164f2723c.png)

```
    fb_page.put_wall_post("Hello there!", {
                            "name" => "Link name",
                            "link" => absolute_url(uri),
                            "caption" => "{*actor*} posted a new review",
                            "description" => "This is a longer description of the attachment",
                            # "picture" => "http://www.example.com/thumbnail.jpg"
                          })
```
