### ISSUE TITLE
サイドバーに「メンバーの検索」も用意する

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#194]
「課題の検索」に加えて「メンバーの検索」も用意する。

スキルごとにリンクを作ればよいと考えるが、スキルはめちゃくちゃ多くなる可能性があるので折りたためるようにする。

**Comment by ibexorg** [comment]
サイドバーの「メンバーの検索」に、今ある「登録メンバー一覧」のページヘのリンクで済むのかな？？

**Comment by PharaohKJ** [comment]
とりあえず、それでまずは済むとは思います＜登録メンバ一覧へのリンクを作るだけでもよい
プルダウンメニューのなかにあるとなかなか押しづらいかなあと。

あとダッシュボードに「スキルを持つ人を検索する」ボタンも作りたいなあ。
