### ISSUE TITLE
okinawa.ha4go.net を導入したい

### ISSUE THREAD

**Issue by kimihito** [codeforkanazawa-org/ha4go#224]
- 団体名と連絡先

Code for Okinawa / tatsuro@mntk.info

- 設定したい団体名( <団体名>.ha4go.net となります)

okinawa.ha4go.net 

- IPアドレスもしくはCNAME

okinawa.ha4go.net.herokudns.com

**Comment by kimihito** [comment]
@PharaohKJ さん（でいいんですかね？）ご検討の方お願いします 🙇

**Comment by PharaohKJ** [comment]
ご連絡ありがとうございます。

@kiyohara さん @kenchif さんおねがいします。

**Comment by kiyohara** [comment]
@kimihito @PharaohKJ CNAME 割り当てで対応しました。ご確認下さい。

http://okinawa.ha4go.net/

※動作確認したらクローズください :)

**Comment by kimihito** [comment]
https://okinawa.ha4go.net で動作確認ができたのでクローズします！

@kiyohara さんご対応ありがとうございました 🙏
