### ISSUE TITLE
Fbのシェア画面で、公開範囲の選択が画面外にでてしまう。

### ISSUE THREAD

**Issue by ibexorg** [codeforkanazawa-org/ha4go#56]
![screenshot from 2015-08-30 11-44-59](https://cloud.githubusercontent.com/assets/7151911/9565482/09baeff4-4f0d-11e5-983f-4d1c6c9bcd4d.png)
![screenshot from 2015-08-30 11-45-38](https://cloud.githubusercontent.com/assets/7151911/9565483/2a9feb34-4f0d-11e5-86f5-f9d59fc6589a.png)

他のサイトとはちょっと様子が違うようなので..

**Comment by PharaohKJ** [comment]
簡単に再現するけど、謎がとけない。いったんpending.

**Comment by ibexorg** [comment]
これ直ってますね。クローズしますか？

**Comment by PharaohKJ** [comment]
おそらく、Facebook SDKのほうがなおしてくれたんじゃないかなぁと予想。close しておきます。
