### ISSUE TITLE
Sakura の上にデプロイ環境を作成する

### ISSUE THREAD

**Issue by kiyohara** [codeforkanazawa-org/ha4go#60]
- [x] Rails の環境作成
- [x] Nagios / munin のセットアップ
- [x] 証明書の確保とセットアップ
- [ ] jenkins のセットアップ

**Comment by PharaohKJ** [comment]
さくらクラウドインスタンスを借りて設定中。
これらの詳細設定については加藤まで。

**Comment by kiyohara** [comment]
- [ ] 情報の共有スキームを確立する

> 認証情報等の秘密情報を含む

**Comment by PharaohKJ** [comment]
とりま muninの設定、サービス停止したら slack に通知するように設定してある。
情報共有は @PharaohKJ まで。GitHub以外の秘密のソーシャルコーディングサービスのプライベート
なところにまとめています。 @kiyohara さん、 @izawa さん、 @ibexorg さんも invite して共有済み。
デプロイ手順もそこに書いてあるとおりやればいいたんよい。

jenkins が動くほどいいインスタンスは遠慮して借りてないですが、いったんこれでどうでしょうか。
問題あったら再オープンしてください。
