### ISSUE TITLE
SMTP の本番環境作成

### ISSUE THREAD

**Issue by kiyohara** [codeforkanazawa-org/ha4go#61]
> すでに利用するメアドとサーバ、アカウントは決定済み

- [ ] Sakura のデプロイ環境から送信できるようにする

**Comment by PharaohKJ** [comment]
35b4b40bba022a2b655acd5b0d9b89491018708a で対応したけれど、sakuraでは未テスト。
詳細なsmtp情報についてはinfra詳細に記載(記載先は私まで問い合わせてください)

**Comment by PharaohKJ** [comment]
終わってます。何かあったら @pharaohkj まで。
