### ISSUE TITLE
メールの送信方法の修正

### ISSUE THREAD

**Issue by kiyohara** [codeforkanazawa-org/ha4go#69]
送信は BCC でおくること
TO には、ググってそれっぽいのをいれる
キーワードは「あんそりさいてっど」

**Comment by PharaohKJ** [comment]
そもそも unsolicited なメールがどうやら世間受けが悪いみたいで、送られないようです。
ActionMailer自体がtoがnilな場合というのが未対応。

とりあえず to でループして送りますが、active_jobに対応させないと根本的に解決しないです。

参考)
http://qiita.com/QUANON/items/09c87787df6b0d287896

**Comment by PharaohKJ** [comment]
うーん。 heroku はactive_jobは有料ぽい。ちょっと環境変数とかみて、`deliver_now` するか `deliver_later` するか考えるようにしないとつまんないかも。

**Comment by PharaohKJ** [comment]
`deliver_later` に対応しました。 heroku も 対応できた。

```
$ heroku ps:scale worker=1
```

上記コマンドで worker 付きにスケールできました。

```
[pharaohkj]$ heroku ps
=== web (1X): bin/rails server -p $PORT -e $RAILS_ENV (1)
web.1: up 2017/05/13 19:14:58 +0900 (~ 14m ago)

=== worker (1X): bundle exec rake jobs:work (1)
worker.1: up 2017/05/13 19:14:55 +0900 (~ 14m ago)
```

上記 README.md に書いたらクローズ予定

**Comment by PharaohKJ** [comment]
64265c5df033965bb3d962409eb6aabae8c8c599 のときに書いてありました。
