### ISSUE TITLE
ドメイン関連の準備をする

### ISSUE THREAD

**Issue by kiyohara** [codeforkanazawa-org/ha4go#70]
* [x] 決定する（α２のタイミングでFacebook上で合意）
  * ドメインは本当に必要か
  * code for kanazawa のサブドメインでよいかも
* [x] 取得する（かとう→請求問題は福島さんと調整）
* [x] 設定する（かとう）
* [x] Facebook アプリの設定に当該ドメインを割り当てる（かとう）

**Comment by PharaohKJ** [comment]
終わってます。何かあったら @pharaohkj まで。
