### ISSUE TITLE
システム送信メールの内容に誤送信向けフォローアップを追記する

### ISSUE THREAD

**Issue by kiyohara** [codeforkanazawa-org/ha4go#75]
メアドを間違えて登録した場合とかに対応する必要がある。
さしあたっては「身に覚えのない人は、こちらからご連絡ください」ぐらいの。

**Comment by PharaohKJ** [comment]
破棄してくださいにしちゃってます。
こちら is どこにしましょうか？

**Comment by ibexorg** [comment]
今後ha4goからこのようなメールを受けとりたくない場合は、ha4goにログインし、マイページよりメールアドレスを削除してください。
Code for Kanazawa ha4go project team.

で編集されるようになりましたので、こちらはクローズします。
