### ISSUE TITLE
ロゴマークがhttp(not https)じゃないのでブラウザで鍵マークつかない

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#80]
http://www.codeforkanazawa.org/images/logo.png

を ドメインにhttps 対応してもらう、か、ha4go内に取り込む。・・・か、新デザインをもう入れてしまう。

どうでしょう？いったん https対応について CfKの担当の方に見解をいただきたいです。

@kenchif @izawa @kiyohara さんかな？

**Comment by izawa** [comment]
https担当というわけではありませんが。。
www.codeforkanazawa.org もいずれhttps対応にしないといけないと思いますが、そこが現状で特にスケジュールされているissueではないことを考えると、ha4go内に取り込むのがいいかも。
どうでしょ。

**Comment by PharaohKJ** [comment]
レスありがとうございます。

わかりました。次のアップデートで中に取り込んじゃいます。
2016年3月31日(木) 19:34 いざわゆきみつ (Yukimitsu Izawa) <notifications@github.com>:

**Comment by PharaohKJ** [comment]
ユーザー顔画像が http で鍵ついてない件。

https://github.com/mkdynamic/omniauth-facebook の `secure_image_url` オプションで対応できそう。

**Comment by PharaohKJ** [comment]
んー。だめぽ。再検討。

**Comment by PharaohKJ** [comment]
ちゃんととれてました。すでにログイン済みユーザーの場合、新しいURLで保存しないので、対応できていないと勘違いしました。

既存のレコードをどうするか置き換えられれば完了。

**Comment by PharaohKJ** [comment]
`image="https://graph.facebook.com/827057854050074/picture"`

**Comment by kiyohara** [comment]
既存のユーザーについては https 付きに手で変更する

**Comment by PharaohKJ** [comment]
変更した。 close
