### ISSUE TITLE
google analytics あたりで統計をとる

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#83]
アカウント含めて要相談。

**Comment by PharaohKJ** [comment]
a3ec690de371386be01cd8d1703784cdcd98b3f3

で対応。現時点では私のgoogle アカウントで GA 設定しました。共有設定で運用します。

CfKのどなたかと共有設定して、共有できたらこの issue をクローズお願いします。
@izawa @kiyohara @kenchif すみませんがご対応をお願いします。

**Comment by kiyohara** [comment]
@PharaohKJ 承知です。GA に設定して欲しいアカウント情報（メールアドレス）を slack でご連絡するようにしますね。

**Comment by PharaohKJ** [comment]
@kiyohara invite しました。フルアクセスで！

**Comment by kiyohara** [comment]
@PharaohKJ 確認できました。 @izawa @kenchif @ibexorg も入っておくのが良いと思うので、 slack なりで @PharaohKJ サンにご連絡くださいマセ :smile:

**Comment by PharaohKJ** [comment]
@kenchif さんを invite しました。確認できましたら、この issue を close してください。

**Comment by kenchif** [comment]
確認できました。ありがとうございます。close致します。
