### ISSUE TITLE
travis-ci に対応させる

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#86]
@jshimazu さんが設定しておいてくれてるが、テストを通せない。

とりあえずやっぱり develop は MySQL じゃなくて SQLite にしておかないといけないかも。

**Comment by PharaohKJ** [comment]
さすがに機能が増えてきたらテストがダルイ。

- ログイン
- 非ログイン

で全ページめぐって 2xx がかえってくるかどうかの確認ぐらいは自動でしたい。

**Comment by kimihito** [comment]
💭  #175 がマージされたらここやろうかなと思ってます（アサインしたかったが自分ではできなかったのでコメントにて…）

**Comment by PharaohKJ** [comment]
https://github.com/codeforkanazawa-org/ha4go/tree/feature/support-rspec-with-travis

で進めている。

**Comment by PharaohKJ** [comment]
@kimihito さんが https://github.com/codeforkanazawa-org/ha4go/pull/176 で進めていただいているので、いったんこれはそのブランチで travis CI がOKをかえすのをゴールとしてそのpr(ブランチ)上で進めます。
