### ISSUE TITLE
ドメインのIPアドレス割り当てを複数人でできるようにする

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#88]
`*.ha4go.net` 、`ha4go.net` のIPアドレス割り当てを @kenchif さんに依頼せずとも、インフラ整備担当者ができるようにしたい。

**Comment by PharaohKJ** [comment]
これ、 @kiyohara さんもできるようになったんですよね？OKそうなら @kiyohara さん close お願いします。

**Comment by kiyohara** [comment]
@kenchif さんにアカウント情報を教えてもらい、清原が対応できるような体制になっています。
クローズしますね。
