### ISSUE TITLE
Facebookでログインできない場合がある

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#90]
Chrome で再現。 JavaScript コンソールに

`FB.login() called before FB.init()` 旨、表示される。

![2016-04-16 10 50 35](https://cloud.githubusercontent.com/assets/1581985/14578407/6f279cc4-03c2-11e6-91d5-0be5550acdf8.png)

**Comment by ibexorg** [comment]
私Chromeしか使ってないですが、これ結構な頻度で遭遇しています...

**Comment by ibexorg** [comment]
今は再現しないようになりました。いったんクローズしますね。
