### ISSUE TITLE
課題のある程度分類を行う

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#94]
ダッシュボードを作成。ログインしたらそのページ。

画面左に検索条件を示したボタンを設ける。それらの仕様は以下

- [x] 最近の課題 直近30日以内(閾値・変更可）にコメントがあった課題
- [x] 話題になっている課題 課題別に直近のコメントが100件(閾値・変更可）のうち、上位ランクをつけ3位以内(閾値・変更可）。
- [x] スキル募集中の課題 課題のステータスのうち、募集中のもの。
- [x] すべての課題

**Comment by ibexorg** [comment]
最小限は”すべての課題”でOK

**Comment by PharaohKJ** [comment]
対応してデプロイ済みですので確認してクローズしてください。

**Comment by ibexorg** [comment]
確認できました。ありがとうございます。
