### ISSUE TITLE
課題ステータスのマスタ化

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#95]
課題ステータスはシステム固定とする。

新規に増やしたい場合には運営に連絡できるようにする。

**Comment by ibexorg** [comment]
Release-201607ではとりあえず全部システム固定としますが、次回以降のどこかのイテレーションでシステム固定フェーズ＋課題（プロジェクト毎）に決めるフェーズの組み合わせにしたいと思っています。ですので今回は一旦固定としたいですが、次回以降はプロジェクト毎に登録できる機能とフェーズの順番を設定できる機能を検討したいと思っています。（メモ的な書き込みです）

**Comment by PharaohKJ** [comment]
@ibexorg さん、「システム固定にする値一覧」ってどこかにありましたっけ？

**Comment by ibexorg** [comment]
そう言われると作ってなかったような気がします。今晩、とりあえず版をコメントします。

**Comment by PharaohKJ** [comment]
まぁとりあえずはこのままでいいんじゃないでしょうか？
今週木曜日、議題としてあげましょう。現状は

https://github.com/codeforkanazawa-org/ha4go/blob/master/db/seeds.rb

が、いったんアプリ作った時の初期値です。現状は以下のようになっています。

skill (技術)

| id | name                                    |
|---:|:----------------------------------------|
|  1 | C++                                     |
|  2 | Ruby                                    |
|  3 | JavaScript                              |
|  4 | RoR                                     |
|  5 | GoLang                                  |
|  6 | HTML                                    |
|  7 | Java                                    |
|  8 | Python                                  |
|  9 | Scala                                   |
| 10 | PHP                                     |
| 11 | Perl                                    |
| 12 | C                                       |
| 13 | TeX                                     |
| 14 | LISP                                    |
| 15 | 対人スキル                              |
| 17 | コミュニティオーガナイザー              |
| 18 | イベントオーガナイザー                  |
| 19 | デリバリーリード                        |
| 20 | データエヴァンジェリスト                |
| 21 | プランニング                            |
| 22 | プログラミング                          |
| 23 | デザイン                                |
| 24 | ライティング                            |
| 25 | IoT                                     |
| 26 | DeepLearning                            |
| 27 | 動物生態学                              |
| 28 | 狩猟免許                                |

stage(段階、現在は1つしかつけられないが、複数タグつけられるようになる予定)

| id | name                     |
|---:|:-------------------------|
|  1 | 議論                     |
|  2 | 企画・設計               |
|  3 | プロトタイプ作成         |
|  4 | ユーザテスト             |
|  5 | 運用                     |
|  6 | 改善・改修               |
|  7 | 参加者募集               |
|  8 | デザイナー募集           |
|  9 | エンジニア募集           |

**Comment by ibexorg** [comment]
皆さんと話合ってみたいですが、
私のイメージとしては今のstageの１〜６はシステム固定で課題毎に必ず一つ選ぶ。
それ以外の募集..のようなものは任意でつけてもらえればよいと思っています。
skillについては特別固定は必要ないかと思っていますが、よくよく考えると同じようにシステム固定の職業は必ず選ぶ、ってルールにしても良いかな...
木曜日に話してみましょう。

**Comment by PharaohKJ** [comment]
結局、どうなりましたっけ？バックログの更新もないようですが。 @ibexorg さん、確認 & バックログ更新お願いします。

**Comment by ibexorg** [comment]
すみません、このチケットはstageの1〜6のみの固定にしていただいて完了としたいです。
残りの"募集"はタグ(任意入力)にし、タグ..に関しては別チケットで7月リリースには含めずバックログに別途書きます。

**Comment by kiyohara** [comment]
実装は完了しているので、 @ibexorg さんが動作確認する。

**Comment by ibexorg** [comment]
惜しい!
"参加者募集"、"デザイナー募集"、"エンジニア募集"は除いてくださいー

あと..ごめんなさい..今のステータスは過去に一旦決めていましたが、何となく違和感があるので...
id.名前
1.議論・調査
2.企画・設計
3.試作・開発
4.検証・評価
5.運用・保守
6.改善・改修
7.休止・終了

休止・終了は今後機能的に意味を持たせたい（参加できなくなるし、フォローを書けなくなる等）ものです。今は意味を持たせなくてよいです。
一般向けでなるべく横文字はやめたかったのですが、これはこれで表現硬いでしょうかね？？

**Comment by PharaohKJ** [comment]
なんというか 2. 3. 4. 5. 6. あたりは別に区別しなくてもいいんじゃあないかと考えたりします。
表現硬いというかやり方が硬いなあ、ウォーターフォール？という気持ちがわいてきます。
まぁ細かく別れてるほうが「次何すればいいのか」伝わっていいかもしれませんね。

- 議論と調査
- 企画と試作中
- 運用中
- 休止・終了

このぐらいでいいような気もします。各フェーズの説明文があるといいのかも。ヘルプページを
作成してほしいです。

2016年7月16日(土) 23:43 takashi torige <notifications@github.com>:

**Comment by PharaohKJ** [comment]
ああ、思い出した。そうこのフェーズの説明文がいるでしょう？ということでトップページ作りましょうとか考えたのでした。

それはおいておいて、バックログの

スキル募集中の課題 課題のステータスのうち、募集中のもの。

は、 @ibexorg さんのご提示されている1-7のうちどれですか？？
あ、募集はこのステータスとは別に作って、そこを作るところから、という認識でよいですか？

**Comment by PharaohKJ** [comment]
@ibexorg 催促！

**Comment by ibexorg** [comment]
- 議論と調査
- 企画と試作中
- 運用中
- 休止・終了
にいったん決めましょう。
あと、「休止・終了」以外は募集スキルが１つでも登録されていた場合「スキル募集中の課題」という定義にしましょうか。

**Comment by PharaohKJ** [comment]
対応してデプロイ済みですので確認してクローズしてください。

**Comment by ibexorg** [comment]
確認できました。ありがとうございます。
