### ISSUE TITLE
課題更新メールにコメントを含める

### ISSUE THREAD

**Issue by PharaohKJ** [codeforkanazawa-org/ha4go#99]
メール本文にコメントの一部分を入れる。(50〜100)

**Comment by PharaohKJ** [comment]
255文字まで表示するようにしました。

**Comment by PharaohKJ** [comment]
文面を相談させてください。

**Comment by PharaohKJ** [comment]
現在のは https://github.com/codeforkanazawa-org/ha4go/blob/master/config/locales/views/project_mailer/ja.yml

**Comment by PharaohKJ** [comment]
誰による更新なのかメールでわからない。

**Comment by ibexorg** [comment]
コメントが入ることを確認しましたが、
#96 でコメントにURLをつけた場合、タグも入ってしまいました。

**Comment by PharaohKJ** [comment]
そうか、私 htmlメールでしか確認してませんでした。textも考慮しないといけませんね。

**Comment by PharaohKJ** [comment]
文面を完全に決める

**Comment by ibexorg** [comment]
件名：[ha4go](%課題名の先頭20文字分%)に更新がありました。
※課題名が20文字以上の場合、末尾に"..."をつける

本文：
%本文を記載%

----ここ<HR>-------------------------------------------------------------------------------------------------------------
今後ha4goからこのようなメッセージを受けとりたくない場合は、プロフィールよりメールアドレスを削除してください。
Code for Kanazawa ha4go project team

くらいでいかがでしょう。

**Comment by PharaohKJ** [comment]
対応しました。次の更新時にテストしてください。

**Comment by PharaohKJ** [comment]
http://railsguides.jp/action_mailer_basics.html
textも含めたマルチパートにしたい。

**Comment by ibexorg** [comment]
文面更新されていることは確認しました。

以下文面
今後ha4goからこのようなメールを受けとりたくない場合は、ha4goにログインし、マイページよりメールアドレスを削除してください。
Code for Kanazawa ha4go project team.

**Comment by ibexorg** [comment]
あれ？PC版のメールは問題ないのですが、androidのメーラーが変です。
箇条書きの部分にリンクが。
![screenshot_20160716-234825](https://cloud.githubusercontent.com/assets/7151911/16895420/853b6ab4-4bb0-11e6-8109-3d264195a424.png)

**Comment by PharaohKJ** [comment]
私の Nexus 7 (6.0.1) の inbox と gmail で確認しましたが再現せず、わかりませんでした。
iOSのメール、 inbox 、 gmail でも再現せず、わかりません。

どこへのリンクになっているでしょうか？ドットがあるとリンクになってしまうお使いのメーラのバグだとか？

**Comment by ibexorg** [comment]
これはAndroidのメーラのバグ？でした。.(ドット)がつくと、指摘通りアンカー表示になりました。
ですのでこの件はクローズしますね。
